<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Calculator_Wpf</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>calc.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="calc.ico" />
  </ItemGroup>

</Project>
